version: '3.9'
services:
  cacttus-core-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - 'POSTGRES_USER=alternative'
      - 'POSTGRES_PASSWORD=alternative'
      - 'POSTGRES_DB=alternativeDb'
    ports:
      - '5436:5432'